/obj/structure/machinery/cm_vending/sorted/uniform_supply/squad_prep/uscm_ground
	name = "\improper ColMarTech Outpost Uniform Vendor"
	desc = "An automated supply rack hooked up to a small storage of standard marine uniforms."
	icon_state = "uscm_gear"
	req_access = list(ACCESS_MARINE_PREP)
	req_one_access = list()
	listed_products = list()
	hackable = TRUE
	vend_flags = VEND_CLUTTER_PROTECTION | VEND_LIMITED_INVENTORY | VEND_TO_HAND | VEND_STOCK_DYNAMIC

/obj/structure/machinery/cm_vending/sorted/uniform_supply/squad_prep/uscm_ground/ui_state(mob/user)
	return GLOB.not_incapacitated_and_adjacent_strict_state

/obj/structure/machinery/cm_vending/sorted/uniform_supply/squad_prep/uscm_ground/populate_product_list(scale)
	listed_products = list(
		list("STANDARD EQUIPMENT", -1, null, null, null),
		list("Marine Combat Boots", floor(scale * 15), /obj/item/clothing/shoes/marine/knife, VENDOR_ITEM_REGULAR),
		list("Marine Uniform, Jungle BDU", floor(scale * 15), /obj/item/clothing/under/marine/standard, VENDOR_ITEM_REGULAR),
		list("Marine Combat Gloves", floor(scale * 15), /obj/item/clothing/gloves/marine, VENDOR_ITEM_REGULAR),
		list("Copperheads Section Radio Headset", floor(scale * 15), /obj/item/device/radio/headset/almayer/marine/solardevils/uscm_ground/copperheads, VENDOR_ITEM_REGULAR),
		list("Rattlesnakes Section Radio Headset", floor(scale * 15), /obj/item/device/radio/headset/almayer/marine/solardevils/uscm_ground/rattlesnakes, VENDOR_ITEM_REGULAR),
		list("M5 Pattern Camera Headset", floor(scale * 15), /obj/item/device/overwatch_camera, VENDOR_ITEM_REGULAR),
		list("Utility Cap, Jungle", floor(scale * 15), /obj/item/clothing/head/cmcap, VENDOR_ITEM_REGULAR),
		list("Expedition Cap, Jungle", floor(scale * 15), /obj/item/clothing/head/cmcap/flap, VENDOR_ITEM_REGULAR),
		list("Boonie Hat, Jungle", floor(scale * 15), /obj/item/clothing/head/cmcap/boonie, VENDOR_ITEM_REGULAR),
		list("Durag, Jungle", floor(scale * 15), /obj/item/clothing/head/durag, VENDOR_ITEM_REGULAR),
		list("Bandana, Jungle", floor(scale * 15), /obj/item/clothing/head/cmbandana, VENDOR_ITEM_REGULAR),
		list("Beanie, Jungle", floor(scale * 15), /obj/item/clothing/head/beanie/green, VENDOR_ITEM_REGULAR),

		list("WEBBINGS", -1, null, null),
		list("M3 Pattern Webbing", 2, /obj/item/clothing/accessory/storage/webbing/m3, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Magazine Webbing", 2, /obj/item/clothing/accessory/storage/webbing/m3/mag, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Shotgun Shell Webbing", 2, /obj/item/clothing/accessory/storage/webbing/m3/shotgun, VENDOR_ITEM_REGULAR),
		list("M3 Pattern M40 Webbing", 0.75, /obj/item/clothing/accessory/storage/webbing/m3/m40, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Small Pouch Webbing", 2, /obj/item/clothing/accessory/storage/webbing/m3/small, VENDOR_ITEM_REGULAR),
		list("Drop Pouch", 4, /obj/item/clothing/accessory/storage/droppouch, VENDOR_ITEM_REGULAR),
		list("Leg Pouch", 4, /obj/item/clothing/accessory/storage/smallpouch, VENDOR_ITEM_REGULAR),
		list("Shoulder Holster", round(max(1,(scale * 0.5))), /obj/item/clothing/accessory/storage/holster, VENDOR_ITEM_REGULAR),

		list("ARMOR", -1, null, null),
		list("M10 Pattern Marine Helmet", floor(scale * 15), /obj/item/clothing/head/helmet/marine, VENDOR_ITEM_REGULAR),
		list("Standard M3 Pattern Armor Set", round(scale * 15), /obj/item/storage/box/guncase/m3armor, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Chestpiece", round(scale * 10), /obj/item/clothing/suit/marine, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Ridged Chestpiece", round(scale * 10), /obj/item/clothing/suit/marine/lines, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Smooth Chestpiece", round(scale * 10), /obj/item/clothing/suit/marine/smooth, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Pauldrons", round(scale * 10), /obj/item/clothing/accessory/pads, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Lap Panel", round(scale * 10), /obj/item/clothing/accessory/pads/groin, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Greaves", round(scale * 15), /obj/item/clothing/accessory/pads/greaves, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Kneepads", round(scale * 15), /obj/item/clothing/accessory/pads/kneepads, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Vambraces", round(scale * 10), /obj/item/clothing/accessory/pads/bracers, VENDOR_ITEM_REGULAR),
		list("M3 Pattern Gorget", round(scale * 15), /obj/item/clothing/accessory/pads/neckguard, VENDOR_ITEM_REGULAR),

		list("BACKPACK", -1, null, null, null),
		list("Lightweight IMP Backpack", floor(scale * 15), /obj/item/storage/backpack/marine, VENDOR_ITEM_REGULAR),
		list("Technician Backpack", floor(scale * 15), /obj/item/storage/backpack/marine/tech, VENDOR_ITEM_REGULAR),
		list("USCM Satchel", floor(scale * 15), /obj/item/storage/backpack/marine/satchel, VENDOR_ITEM_REGULAR),
		list("USCM Technical Satchel", floor(scale * 15), /obj/item/storage/backpack/marine/satchel/tech, VENDOR_ITEM_REGULAR),

		list("RESTRICTED BACKPACKS", -1, null, null),
		list("Radio Telephone Backpack", 0.75, /obj/item/storage/backpack/marine/satchel/rto, VENDOR_ITEM_REGULAR),

		list("BELTS", -1, null, null),
		list("M276 Pattern Ammo Load Rig", floor(scale * 15), /obj/item/storage/belt/marine, VENDOR_ITEM_REGULAR),
		list("M276 Pattern M40 Grenade Rig", floor(scale * 10), /obj/item/storage/belt/grenade, VENDOR_ITEM_REGULAR),
		list("M276 Pattern General Pistol Holster Rig", floor(scale * 15), /obj/item/storage/belt/gun/m4a3, VENDOR_ITEM_REGULAR),
		list("M276 Pattern General Revolver Holster Rig", floor(scale * 15), /obj/item/storage/belt/gun/m44, VENDOR_ITEM_REGULAR),
		list("M276 Pattern M82F Holster Rig", floor(scale * 5), /obj/item/storage/belt/gun/flaregun, VENDOR_ITEM_REGULAR),
		list("M276 G8-A General Utility Pouch", floor(scale * 15), /obj/item/storage/backpack/general_belt, VENDOR_ITEM_REGULAR),

		list("POUCHES", -1, null, null, null),
		list("First-Aid Pouch", floor(scale * 15), /obj/item/storage/pouch/firstaid, VENDOR_ITEM_REGULAR),
		list("Flare Pouch (Full)", floor(scale * 15), /obj/item/storage/pouch/flare/full, VENDOR_ITEM_REGULAR),
		list("Large Magazine Pouch", floor(scale * 15), /obj/item/storage/pouch/magazine/large, VENDOR_ITEM_REGULAR),
		list("Medium General Pouch", floor(scale * 15), /obj/item/storage/pouch/general/medium, VENDOR_ITEM_REGULAR),
		list("Large Pistol Magazine Pouch", floor(scale * 15), /obj/item/storage/pouch/magazine/pistol/large, VENDOR_ITEM_REGULAR),
		list("Pistol Pouch", floor(scale * 15), /obj/item/storage/pouch/pistol, VENDOR_ITEM_REGULAR),

		list("RESTRICTED POUCHES", -1, null, null, null),
		list("Explosive Pouch", 1.25, /obj/item/storage/pouch/explosive, VENDOR_ITEM_REGULAR),
		list("First Responder Pouch", 2.5, /obj/item/storage/pouch/first_responder, VENDOR_ITEM_REGULAR),
		list("Tools Pouch", 1.25, /obj/item/storage/pouch/tools, VENDOR_ITEM_REGULAR),
		list("Sling Pouch", 1.25, /obj/item/storage/pouch/sling, VENDOR_ITEM_REGULAR),
		list("Incinerator Fuel Tank Pouch", 1.25, /obj/item/storage/pouch/flamertank, VENDOR_ITEM_REGULAR),
		list("Shotgun Shell Pouch", 1.25, /obj/item/storage/pouch/shotgun, VENDOR_ITEM_REGULAR),
		list("Machete Pouch", 1.25, /obj/item/storage/pouch/machete/full,  VENDOR_ITEM_REGULAR),

		list("MASK", -1, null, null, null),
		list("M5 Gas Mask", floor(scale * 15), /obj/item/clothing/mask/gas/military, VENDOR_ITEM_REGULAR),
		list("Tactical Wrap", floor(scale * 10), /obj/item/clothing/mask/rebreather/scarf/tacticalmask, VENDOR_ITEM_REGULAR),
		list("Heat Absorbent Coif", floor(scale * 10), /obj/item/clothing/mask/rebreather/scarf, VENDOR_ITEM_REGULAR),

		list("MISCELLANEOUS", -1, null, null, null),
		list("Ballistic goggles", round(scale * 10), /obj/item/clothing/glasses/mgoggles, VENDOR_ITEM_REGULAR),
		list("Ballistic goggles, sun-shaded", round(scale * 10), /obj/item/clothing/glasses/mgoggles/black, VENDOR_ITEM_REGULAR),
		list("Ballistic goggles, laser-shaded (brown)", round(scale * 10), /obj/item/clothing/glasses/mgoggles/orange, VENDOR_ITEM_REGULAR),
		list("Ballistic goggles, laser-shaded (green)", round(scale * 10), /obj/item/clothing/glasses/mgoggles/green, VENDOR_ITEM_REGULAR),
		list("M10 Helmet Jungle Cover", round(scale * 10), /obj/item/prop/helmetgarb/camocover, VENDOR_ITEM_REGULAR),
		list("M10 Helmet Snow Cover", round(scale * 10), /obj/item/prop/helmetgarb/camocover/snow, VENDOR_ITEM_REGULAR),
		list("M10 Helmet Desert Cover", round(scale * 10), /obj/item/prop/helmetgarb/camocover/desert, VENDOR_ITEM_REGULAR),
		list("M10 Helmet Netting", round(scale * 10), /obj/item/prop/helmetgarb/netting, VENDOR_ITEM_REGULAR),
		list("M10 Helmet Rain Cover", round(scale * 10), /obj/item/prop/helmetgarb/raincover, VENDOR_ITEM_REGULAR),
		list("USCM Shoulder Patch", round(scale * 15), /obj/item/clothing/accessory/patch, VENDOR_ITEM_REGULAR),
		list("Firearm Lubricant", round(scale * 15), /obj/item/prop/helmetgarb/gunoil, VENDOR_ITEM_REGULAR),
		list("LRRP Bedroll", round(scale * 15), /obj/item/roller/bedroll, VENDOR_ITEM_REGULAR),
		list("Marine Issue Compass", round(scale * 15), /obj/item/prop/helmetgarb/compass, VENDOR_ITEM_REGULAR),
		)

GLOBAL_LIST_INIT(cm_vending_marine_px_snowflake, list(

	list("NON-STANDARD CLOTHING", 0, null, null, null),
	list("Jungle Combat Boots", 20, /obj/item/clothing/shoes/marine/civilian/jungle, null, VENDOR_ITEM_REGULAR),
	list("Brown Combat Boots", 20, /obj/item/clothing/shoes/marine/civilian/brown, null, VENDOR_ITEM_REGULAR),
	list("Brown Combat Gloves", 20, /obj/item/clothing/gloves/marine/brown, null, VENDOR_ITEM_REGULAR),
	list("Combat Gloves (Fingerless)", 20, /obj/item/clothing/gloves/marine/fingerless, null, VENDOR_ITEM_REGULAR),
	list("Brown Combat Gloves (Fingerless)", 20, /obj/item/clothing/gloves/marine/brown/fingerless, null, VENDOR_ITEM_REGULAR),
	list("Shotgun Holster Belt", 80, /obj/item/storage/belt/gun/shotgunholster, null, VENDOR_ITEM_REGULAR),
	list("M67 Flak Jacket (Blue)", 30, /obj/item/clothing/accessory/flak, null, VENDOR_ITEM_REGULAR),
	list("M67 Flak Jacket (Green)", 30, /obj/item/clothing/accessory/flak/od, null, VENDOR_ITEM_REGULAR),
	list("Windbreaker, Green", 30, /obj/item/clothing/suit/storage/windbreaker/windbreaker_green, null, VENDOR_ITEM_REGULAR),
	list("Windbreaker, Brown", 30, /obj/item/clothing/suit/storage/windbreaker/windbreaker_brown, null, VENDOR_ITEM_REGULAR),
	list("Windbreaker, Blue", 30, /obj/item/clothing/suit/storage/windbreaker/windbreaker_blue, null, VENDOR_ITEM_REGULAR),
	list("Marine Service Jacket", 30, /obj/item/clothing/suit/storage/jacket/marine/service, null, VENDOR_ITEM_REGULAR),
	list("USCM PT Shorts", 20, /obj/item/clothing/under/shorts/red/uscm, null, VENDOR_ITEM_REGULAR),

	list("EYEWEAR", 0, null, null, null),
	list("Eyepatch", 20, /obj/item/clothing/glasses/eyepatch, null, VENDOR_ITEM_REGULAR),
	list("Green Eyepatch", 20, /obj/item/clothing/glasses/eyepatch/green, null, VENDOR_ITEM_REGULAR),
	list("Marine RPG Glasses", 20, /obj/item/clothing/glasses/regular, null, VENDOR_ITEM_REGULAR),
	list("Prescription Glasses", 20, /obj/item/clothing/glasses/regular/hipster, null, VENDOR_ITEM_REGULAR),
	list("Prescription ballistic goggles", 20, /obj/item/clothing/glasses/mgoggles/prescription, null, VENDOR_ITEM_REGULAR),
	list("Prescription ballistic goggles, sun-shaded", 20, /obj/item/clothing/glasses/mgoggles/black/prescription, null, VENDOR_ITEM_REGULAR),
	list("Prescription ballistic goggles, laser-shaded (brown)", 20, /obj/item/clothing/glasses/mgoggles/orange/prescription, null, VENDOR_ITEM_REGULAR),
	list("Prescription ballistic goggles, laser-shaded (green)", 20, /obj/item/clothing/glasses/mgoggles/green/prescription, null, VENDOR_ITEM_REGULAR),
	list("Aviator shades", 20, /obj/item/clothing/glasses/sunglasses/aviator, null, VENDOR_ITEM_REGULAR),
	list("BiMex Polarized Shades", 30, /obj/item/clothing/glasses/sunglasses/big, null, VENDOR_ITEM_REGULAR),
	list("BiMex Tactical Shades", 30, /obj/item/clothing/glasses/sunglasses/big/orange, null, VENDOR_ITEM_REGULAR),
	list("BiMex Classic Shades", 30, /obj/item/clothing/glasses/sunglasses/big/classic, null, VENDOR_ITEM_REGULAR),
	list("Sunglasses", 20, /obj/item/clothing/glasses/sunglasses, null, VENDOR_ITEM_REGULAR),
	list("Prescription sunglasses", 20, /obj/item/clothing/glasses/sunglasses/prescription, null, VENDOR_ITEM_REGULAR),
	list("Pilot visor, black", 30, /obj/item/device/helmet_visor/po_visor/marine, null, VENDOR_ITEM_REGULAR),
	list("Pilot visor, yellow", 30, /obj/item/device/helmet_visor/po_visor/marine/yellow, null, VENDOR_ITEM_REGULAR),

	list("ARMOR PAINTS", 0, null, null, null),
	list("Black Smartgun Harness Paint", 20, /obj/item/clothing/accessory/paint/sg, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Skull", 20, /obj/item/clothing/accessory/paint, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Heart", 20, /obj/item/clothing/accessory/paint/heart, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, UA Flag", 20, /obj/item/clothing/accessory/paint/uaflag, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, US Flag", 20, /obj/item/clothing/accessory/paint/usflag, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Target", 20, /obj/item/clothing/accessory/paint/target, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Smiley-Face", 20, /obj/item/clothing/accessory/paint/alcoholism, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Neutral-Face", 20, /obj/item/clothing/accessory/paint/melancholy, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Cross", 20, /obj/item/clothing/accessory/paint/cross, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Inscription", 20, /obj/item/clothing/accessory/paint/inscription, null, VENDOR_ITEM_REGULAR),
	list("M3 Pattern Paint, Fire", 20, /obj/item/clothing/accessory/paint/fire, null, VENDOR_ITEM_REGULAR),

	list("HEADWEAR", 0, null, null, null),
	list("USCM Beanie, Grey", 20, /obj/item/clothing/head/headband/intel, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Beanie, Tan", 20, /obj/item/clothing/head/cmcap/boonie/snow, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Boonie Hat, Desert", 20, /obj/item/clothing/head/cmcap/boonie/tan, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Boonie Hat, Snow", 20, /obj/item/clothing/head/cmcap/boonie/snow, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Cap, Desert", 20, /obj/item/clothing/head/cmcap/desert, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Cap, Snow", 20, /obj/item/clothing/head/cmcap/snow, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Operations Cap, Green", 20, /obj/item/clothing/head/cmcap/bridge, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Operations Cap, Tan", 20, /obj/item/clothing/head/cmcap/bridge/tan, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Expedition Flapcap, Desert", 20, /obj/item/clothing/head/cmcap/flap/desert, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Expedition Flapcap, Snow", 20, /obj/item/clothing/head/cmcap/flap/snow, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("USCM Headset", 20, /obj/item/clothing/head/headset, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("Durag, Black", 20, /obj/item/clothing/head/durag/black, null, VENDOR_ITEM_REGULAR),
	list("Beret, Red", 20, /obj/item/clothing/head/beret/cm/red, null, VENDOR_ITEM_REGULAR),
	list("Beret, Black", 20, /obj/item/clothing/head/beret/cm/black, null, VENDOR_ITEM_REGULAR),
	list("Beret, White", 20, /obj/item/clothing/head/beret/cm/white, null, VENDOR_ITEM_REGULAR),
	list("Beret, Red Flash", 20, /obj/item/clothing/head/beret/cm/alpha, null, VENDOR_ITEM_REGULAR),
	list("Beret, Yellow Flash", 20, /obj/item/clothing/head/beret/cm/bravo, null, VENDOR_ITEM_REGULAR),
	list("Beret, Purple Flash", 20, /obj/item/clothing/head/beret/cm/charlie, null, VENDOR_ITEM_REGULAR),
	list("Beret, Blue Flash", 20, /obj/item/clothing/head/beret/cm/delta, null, VENDOR_ITEM_REGULAR),
	list("Beret, Green Flash", 20, /obj/item/clothing/head/beret/cm/echo, null, VENDOR_ITEM_REGULAR),
	list("Beret, Brown Flash", 20, /obj/item/clothing/head/beret/cm/foxtrot, null, VENDOR_ITEM_REGULAR),
	list("Beret, Black Flash", 20, /obj/item/clothing/head/beret/cm/intel, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
	list("Bandana, Brown", 20, /obj/item/clothing/head/headband/brown, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Grey", 20, /obj/item/clothing/head/headband/gray, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Tan", 20, /obj/item/clothing/head/headband/tan, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Red", 20, /obj/item/clothing/head/headband/red, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Orange", 20, /obj/item/clothing/head/headband/bravo, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Purple", 20, /obj/item/clothing/head/headband/charlie, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Blue", 20, /obj/item/clothing/head/headband/delta, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Cyan Green", 20, /obj/item/clothing/head/headband/echo, null, VENDOR_ITEM_REGULAR),
	list("Bandana, Black", 20, /obj/item/clothing/head/headband/intel, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),

	list("MASKS AND SCARVES", 0, null, null, null),
	list("Coif", 20, /obj/item/clothing/mask/rebreather/scarf, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Black)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/black, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Green)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/green, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Grey)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Red)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/red, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Tan)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/tan, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Yellow)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/bravo, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Purple)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/charlie, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Blue)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/delta, null, VENDOR_ITEM_REGULAR),
	list("Wrap (Cyan Green)", 20, /obj/item/clothing/mask/rebreather/scarf/tacticalmask/echo, null, VENDOR_ITEM_REGULAR),
	list("Neckerchief (Black)", 20, /obj/item/clothing/mask/neckerchief/black, null, VENDOR_ITEM_REGULAR),
	list("Neckerchief (Tan)", 20, /obj/item/clothing/mask/neckerchief, null, VENDOR_ITEM_REGULAR),
	list("Neckerchief (Green)", 20, /obj/item/clothing/mask/neckerchief/green, null, VENDOR_ITEM_REGULAR),
	list("Neckerchief (Grey)", 20, /obj/item/clothing/mask/neckerchief/gray, null, VENDOR_ITEM_REGULAR),
	list("Neckerchief (Red)", 20, /obj/item/clothing/mask/neckerchief/red, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Grey)", 20, /obj/item/clothing/mask/tornscarf, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Green)", 20, /obj/item/clothing/mask/tornscarf/green, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Snow)", 20, /obj/item/clothing/mask/tornscarf/snow, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Desert)", 20, /obj/item/clothing/mask/tornscarf/desert, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Urban)", 20, /obj/item/clothing/mask/tornscarf/urban, null, VENDOR_ITEM_REGULAR),
	list("Scarf (Black)", 20, /obj/item/clothing/mask/tornscarf/black, null, VENDOR_ITEM_REGULAR),
	list("Balaclava", 20, /obj/item/clothing/mask/balaclava, null, VENDOR_ITEM_REGULAR),
	list("Balaclava (Green)", 20, /obj/item/clothing/mask/balaclava/tactical, null, VENDOR_ITEM_REGULAR),
	list("USCM Balaclava (Green)", 20, /obj/item/clothing/mask/rebreather/scarf/green, null, VENDOR_ITEM_REGULAR),
	list("USCM Balaclava (Tan)", 20, /obj/item/clothing/mask/rebreather/scarf/tan, null, VENDOR_ITEM_REGULAR),
	list("USCM Balaclava (Grey)", 20, /obj/item/clothing/mask/rebreather/scarf/gray, null, VENDOR_ITEM_REGULAR),
	list("Skull Balaclava, Blue", 60, /obj/item/clothing/mask/rebreather/skull, null, VENDOR_ITEM_REGULAR),
	list("Skull balaclava, Black", 60, /obj/item/clothing/mask/rebreather/skull/black, null, VENDOR_ITEM_REGULAR),

	list("WEAPONS", 0, null, null, null),
	list("M5 Bayonet", 30, /obj/item/attachable/bayonet, null, VENDOR_ITEM_REGULAR),
	list("KA-BAR Utility Knife", 30, /obj/item/weapon/knife/marine/kabar, null, VENDOR_ITEM_REGULAR),
	list("Baker-Pattern Fighting Knife", 30, /obj/item/weapon/knife/marine/baker, null, VENDOR_ITEM_REGULAR),
	list("Type 80 Bayonet", 30, /obj/item/attachable/bayonet/upp/surplus, null, VENDOR_ITEM_REGULAR),
	list("M8 Cartridge Bayonet", 30, /obj/item/storage/box/loadout/co2_knife, null, VENDOR_ITEM_REGULAR),
	list("Bowie Fighting Knife", 40, /obj/item/storage/box/loadout/bowie, null, VENDOR_ITEM_REGULAR),
	list("M2100 Machete", 40, /obj/item/storage/large_holster/machete/arnold/weak, null, VENDOR_ITEM_REGULAR),
	list("Custom M4A3 Pistol", 80, /obj/item/storage/box/loadout/M4A3_custom_loadout, null, VENDOR_ITEM_REGULAR),
	list("M1911 Pistol", 80, /obj/item/storage/box/loadout/M1911_loadout, null, VENDOR_ITEM_REGULAR),
	list("M44 Revolver", 80, /obj/item/storage/box/loadout/M44_loadout, null, VENDOR_ITEM_REGULAR),
	list("Custom M44 Revolver", 80, /obj/item/storage/box/loadout/M44_custom_loadout, null, VENDOR_ITEM_REGULAR),
	list("HG 45 'Aguila' Pistol", 80, /obj/item/storage/box/loadout/HG45_civilian_loadout, null, VENDOR_ITEM_REGULAR),
	list("HG 45 'Marina' Pistol", 80, /obj/item/storage/box/loadout/HG45_marine_loadout, null, VENDOR_ITEM_REGULAR),
	list("HG 44 'Automag' Pistol", 80, /obj/item/storage/box/loadout/HG44_loadout, null, VENDOR_ITEM_REGULAR),
	list("Spearhead Armoury Revolver", 80, /obj/item/storage/box/loadout/Spearhead_loadout, null, VENDOR_ITEM_REGULAR),
	list("Custom Spearhead Armoury Revolver", 80, /obj/item/storage/box/loadout/Spearhead_loadout/custom, null, VENDOR_ITEM_REGULAR),
	list("L54A2 Pistol", 80, /obj/item/storage/box/loadout/L54_loadout, null, VENDOR_ITEM_REGULAR),
	list("M9 Pistol", 80, /obj/item/storage/box/loadout/M9_loadout, null, VENDOR_ITEM_REGULAR),
	list("VP78 Pistol", 80, /obj/item/storage/box/loadout/VP78_loadout, null, VENDOR_ITEM_REGULAR),

	list("HELMET ACCESSORIES", 0, null, null, null),
	list("Flair, Initech", 20, /obj/item/prop/helmetgarb/flair_initech, null, VENDOR_ITEM_REGULAR),
	list("Flair, Io", 20, /obj/item/prop/helmetgarb/flair_io, null, VENDOR_ITEM_REGULAR),
	list("Flair, Peace and Love", 20, /obj/item/prop/helmetgarb/flair_peace, null, VENDOR_ITEM_REGULAR),
	list("Flair, USCM", 20, /obj/item/prop/helmetgarb/flair_uscm, null, VENDOR_ITEM_REGULAR),
	list("Gun Oil", 20, /obj/item/prop/helmetgarb/gunoil, null, VENDOR_ITEM_REGULAR),
	list("Helmet Netting", 20, /obj/item/prop/helmetgarb/netting, null, VENDOR_ITEM_REGULAR),
	list("Lucky Feather, Red", 20, /obj/item/prop/helmetgarb/lucky_feather, null, VENDOR_ITEM_REGULAR),
	list("Lucky Feather, Yellow", 20, /obj/item/prop/helmetgarb/lucky_feather/yellow, null, VENDOR_ITEM_REGULAR),
	list("Lucky Feather, Purple", 20, /obj/item/prop/helmetgarb/lucky_feather/purple, null, VENDOR_ITEM_REGULAR),
	list("Lucky Feather, Blue", 20, /obj/item/prop/helmetgarb/lucky_feather/blue, null, VENDOR_ITEM_REGULAR),
	list("M1 Multispectrum Visor", 20, /obj/item/prop/helmetgarb/helmet_nvg/cosmetic/larp, null, VENDOR_ITEM_REGULAR),
	list("Prescription Bottle", 20, /obj/item/prop/helmetgarb/prescription_bottle, null, VENDOR_ITEM_REGULAR),
	list("Rain cover", 20, /obj/item/prop/helmetgarb/raincover, null, VENDOR_ITEM_REGULAR),
	list("Rabbit's Foot", 20, /obj/item/prop/helmetgarb/rabbitsfoot, null, VENDOR_ITEM_REGULAR),
	list("Rosary", 20, /obj/item/prop/helmetgarb/rosary, null, VENDOR_ITEM_REGULAR),
	list("Spent Buckshot", 20, /obj/item/prop/helmetgarb/spent_buckshot, null, VENDOR_ITEM_REGULAR),
	list("Spent Flechette", 20, /obj/item/prop/helmetgarb/spent_flech, null, VENDOR_ITEM_REGULAR),
	list("Spent Slugs", 20, /obj/item/prop/helmetgarb/spent_slug, null, VENDOR_ITEM_REGULAR),
	list("Cartridge", 20, /obj/item/prop/helmetgarb/cartridge, null, VENDOR_ITEM_REGULAR),
	list("Tickets To Space Jam", 20, /obj/item/prop/helmetgarb/spacejam_tickets, null, VENDOR_ITEM_REGULAR),
	list("Trimmed Barbed Wire", 20, /obj/item/prop/helmetgarb/trimmed_wire, null, VENDOR_ITEM_REGULAR),
	list("10x99mm XM43E1 Casing Pipe", 20, /obj/item/prop/helmetgarb/bullet_pipe, null, VENDOR_ITEM_REGULAR),

	list("MISCELLANEOUS", 0, null, null, null),
	list("Crayon", 10, /obj/item/toy/crayon/rainbow, null, VENDOR_ITEM_REGULAR),
	list("Box of Prideful Crayons", 10, /obj/item/storage/box/pride, null, VENDOR_ITEM_REGULAR),
	list("Camera", 10, /obj/item/device/camera, null, VENDOR_ITEM_REGULAR),
	list("Camera Film", 10, /obj/item/device/camera_film, null, VENDOR_ITEM_REGULAR),
	list("Deck Of Cards, Regular", 10, /obj/item/toy/deck, null, VENDOR_ITEM_REGULAR),
	list("Deck Of Cards, Uno", 10, /obj/item/toy/deck/uno, null, VENDOR_ITEM_REGULAR),
	list("Random Plush", 10, /obj/item/toy/plush/random_plushie, null, VENDOR_ITEM_REGULAR),
	list("USCM Poncho (Green)", 120, /obj/item/clothing/accessory/poncho/green, null, VENDOR_ITEM_REGULAR),
))

/obj/structure/machinery/cm_vending/clothing/marine_px/snowflake
	name = "\improper ColMar Postal Exchange kiosk"
	desc = "A vendor capable of proving a vast swathe of doodads and goodies that any marine in a backline posting might want to get a hold of."
	icon_state = "snowflake"
	show_points = TRUE
	use_snowflake_points = TRUE
	vendor_theme = VENDOR_THEME_USCM
	icon_state = "req_attach"
	req_access = list(ACCESS_MARINE_PREP)
	vend_delay = 1 SECONDS

/obj/structure/machinery/cm_vending/clothing/marine_px/snowflake/get_listed_products(mob/user)
	return GLOB.cm_vending_marine_px_snowflake
