/datum/skills/civilian/researcher
	name = "Civilian Researcher"
	skills = list(
		SKILL_CQC = SKILL_CQC_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_DEFAULT,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_NONE,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_RESEARCH = SKILL_RESEARCH_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_UNTRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/civilian/researcher/linguist //No medical/surgery or research skills.
	name = "Civilian Linguist"
	skills = list(
		SKILL_CQC = SKILL_CQC_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_DEFAULT,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_NONE,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_UNTRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)
