/datum/skills/pfc/uscm_ground //Our ground marines aren't quite as robust as their Distress Signal counterparts.
	name = "Private (Outpost)"
	skills = list(
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED, //They can still construct basic 'cades.
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/combat_medic_pve/uscm_ground
	name = "Combat Medic (Outpost)"
	skills = list(
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/smartgunner/uscm_ground
	name = "Squad Smartgunner (Outpost)"
	skills = list(
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/specialist/uscm_ground
	name = "Squad Weapons Specialist (Outpost)"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/combat_engineer/uscm_ground
	name = "Combat Engineer (Outpost)"
	skills = list(
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/tl/uscm_ground //They are beefier in the outpost.
	name = "Fireteam Leader (Outpost)"
	skills = list(
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_POLICE = SKILL_POLICE_FLASH,//To break up petty squabbles
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
	)

/datum/skills/SL/uscm_ground
	name = "Squad Leader (Outpost)"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,//So they can break up fights.
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_ENGINEER = SKILL_ENGINEER_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
	)

/datum/skills/oco
	name = "Commanding Officer (Outpost)"
	skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,//Command
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,//Support
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_FIREMAN = SKILL_FIREMAN_DEFAULT,//Misc
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
		SKILL_PILOT = SKILL_PILOT_DEFAULT,
	)

/datum/skills/AO //Battlefield doctor/second in command.
	name = "Outpost Adjutant (Outpost)"
	skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,//Command
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,//Combat - Fewer than the OCO.
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_DEFAULT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,//Support - full-on doctor engineer, better than the OCO.
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,//Misc
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
	)
