#define HUMAN_AI_HEALTHITEMS "health"
#define HUMAN_AI_AMMUNITION "ammo"
#define HUMAN_AI_GRENADES "grenades"
#define HUMAN_AI_TOOLS "tools"

#define ACTION_USING_HANDS (1<<0)
#define ACTION_USING_LEGS (1<<1)
#define ACTION_USING_MOUTH (1<<2)

/// Action is completed, delete this and move onto the next ongoing action
#define ONGOING_ACTION_COMPLETED "completed"
/// Action isn't finished, move onto the next ongoing action
#define ONGOING_ACTION_UNFINISHED "unfinished"
/// Action isn't finished, block any further actions from the AI this tick
#define ONGOING_ACTION_UNFINISHED_BLOCK "unfinished_block"

#define ACTION_WEIGHT_HIGHEST_PRIORITY INFINITY
#define ACTION_WEIGHT_CONVERSE 1
#define ACTION_WEIGHT_WALK_MELEE 3
#define ACTION_WEIGHT_TREAT_SELF 4
#define ACTION_WEIGHT_PATROL_WAYPOINTS 4
#define ACTION_WEIGHT_FOLLOW_LEADER 5
#define ACTION_WEIGHT_CHASE_TARGET 6
#define ACTION_WEIGHT_KEEP_DISTANCE 10
#define ACTION_WEIGHT_FIRE_AT_TARGET 10
#define ACTION_WEIGHT_THROW_GRENADE 10
#define ACTION_WEIGHT_ITEM_PICKUP 11
#define ACTION_WEIGHT_MG_NEST 12
#define ACTION_WEIGHT_SELECT_PRIMARY 12
#define ACTION_WEIGHT_SNIPER_NEST 12
#define ACTION_WEIGHT_PRIORITY_ITEM_PICKUP 13
#define ACTION_WEIGHT_RELOAD 13
#define ACTION_WEIGHT_TAKE_COVER 14
#define ACTION_WEIGHT_RUN_AWAY 15
#define ACTION_WEIGHT_RESIST_BURNING 16
#define ACTION_WEIGHT_THROW_BACK_GRENADE 25

#define HUMAN_AI_MAX_PATHFINDING_RANGE 45

GLOBAL_LIST_EMPTY(ai_humans)
